Bookstore: styling
nilab-khwaja/bookstore pull request #5
Opened 2023-09-28 16:48 UTC by nilab-khwaja

- Add any missing JSX elements to the project (without adding extra functionality)
-  final design (this includes all elements + the same styling)

2023-09-28 18:19 UTC, ademibowale requested changes
## STATUS: Changes Required :recycle:

### Hi @nilab-khwaja , 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight 🥇

- Descriptive Pull Request title and summary. ✔️
- Form uses the action and method attribute to integrate with [formspree service](https://formspree.io/html). ✔️
- Input fields have the required attribute to activate the validation ✔️
- Max-length attribute Used on the input ✔️
- Pair-programming collaborative activity ✔️
- Good use of Github flow ✔️

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-28 18:19 UTC, ademibowale commented on src/components/styles/Navbar.module.css
> +}
- [ ] I would suggest you to stick to the ziplin design as much as posible to make your app look professional ,kindly make the TExt Bookstor align with lin bpx as show on the design template . 
- [ ] Your design
![Screenshot 2023-09-28 191307](https://github.com/nilab-khwaja/bookstore/assets/92458236/df6a22e9-7b6a-4392-b07a-589b23422546)

- [ ] Given design
![bookstore](https://github.com/nilab-khwaja/bookstore/assets/92458236/4bce56df-5c6c-4e1c-b18e-51d2d95a4f04)

2023-09-28 18:19 UTC, ademibowale commented on src/components/styles/Book.module.css
> +}
- [ ] I would suggest you to make sure the nav menu to be align with the addbook buyyon as shown on the given design as you can see below you design is different to the original design please kindly stick to the given design as much as possible for user friendly.
- [ ] given design
![bookstore](https://github.com/nilab-khwaja/bookstore/assets/92458236/8e49edb4-4328-4505-92cb-4bfb9b3b9c03)

- [ ] your design
![Screenshot 2023-09-28 191307](https://github.com/nilab-khwaja/bookstore/assets/92458236/012b0a7c-7768-48f8-924b-dbfa8bc44aca)

2023-09-29 08:34 UTC, Johnadibe approved these changes
# Status: Approved ✔️
### Hi @nilab-khwaja👋🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![LeonardoInGatsby](https://user-images.githubusercontent.com/38088818/233992044-ad00b20f-3f2f-4c86-8b94-1e613432af5f.gif)

## Highlights
- Implemented all changes requested by the previous reviewer✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-29 11:22 UTC, merged